default: # see available parameters with command : app/console debug:container --parameters | grep sonata.admin
    sonata.admin.configuration.templates:
        default:
            layout: LibrinfoCoreBundle::standard_layout.html.twig
            user_block: LibrinfoCoreBundle:Block:user_block.html.twig
        replace:
            layout: LibrinfoDecoratorBundle:Admin:layout.html.twig
            user_block: LibrinfoDecoratorBundle:Admin/Block:user_block.html.twig
    sonata_doctrine_orm_admin.templates:
        default:
            form:
                - LibrinfoCoreBundle:Admin/Form:admin_forms.html.twig
        replace:
            form:
                - LibrinfoDecoratorBundle:Admin/Form:admin_forms.html.twig
